const users = [
	{
		id: 1001,
		name: "brayan",
		lastName: "muñoz",
		age: 29,
		gender: "M",
		hobbies: ["correr", "jugar futbol", "aprender", "programar", "enseñar"],
	},
	{
		id: 1012,
		name: "stiven",
		lastName: "quiroz",
		age: 17,
		gender: "M",
		hobbies: ["video juegos", "dormir", "ir de fiesta"],
	},
	{
		id: 1013,
		name: "Luisa",
		lastName: "Gómez",
		age: 28,
		gender: "F",
		hobbies: ["yoga", "leer", "cocinar"],
	},
	{
		id: 1014,
		name: "Ana",
		lastName: "Martínez",
		age: 32,
		gender: "F",
		hobbies: ["senderismo", "pintar", "viajar"],
	},
	{
		id: 1015,
		name: "Pedro",
		lastName: "Hernández",
		age: 24,
		gender: "M",
		hobbies: ["música", "bailar", "deportes"],
	},
	{
		id: 1016,
		name: "Isabel",
		lastName: "López",
		age: 41,
		gender: "F",
		hobbies: ["jardinería", "cine", "manualidades"],
	},
	{
		id: 1017,
		name: "Juan",
		lastName: "Pérez",
		age: 29,
		gender: "M",
		hobbies: ["fotografía", "natación", "idiomas"],
	},
	{
		id: 1018,
		name: "Laura",
		lastName: "Ramírez",
		age: 27,
		gender: "F",
		hobbies: ["dibujo", "ajedrez", "música"],
	},
	{
		id: 1019,
		name: "Carlos",
		lastName: "García",
		age: 35,
		gender: "M",
		hobbies: ["ciclismo", "lectura", "fútbol"],
	},
	{
		id: 1020,
		name: "María",
		lastName: "Rodríguez",
		age: 30,
		gender: "F",
		hobbies: ["cocina", "pintura", "senderismo"],
	},
	{
		id: 1021,
		name: "Daniel",
		lastName: "Vargas",
		age: 22,
		gender: "M",
		hobbies: ["videojuegos", "música", "tenis"],
	},
	{
		id: 1022,
		name: "Paula",
		lastName: "Fernández",
		age: 26,
		gender: "F",
		hobbies: ["baile", "viajar", "fotografía"],
	},
	{
		id: 1023,
		name: "Sergio",
		lastName: "Luna",
		age: 31,
		gender: "M",
		hobbies: ["lectura", "natación", "senderismo"],
	},
	{
		id: 1024,
		name: "Mónica",
		lastName: "Díaz",
		age: 23,
		gender: "F",
		hobbies: ["cocina", "pintura", "baile"],
	},
	{
		id: 1025,
		name: "Andrés",
		lastName: "Mendoza",
		age: 37,
		gender: "M",
		hobbies: ["música", "correr", "viajar"],
	},
	{
		id: 1026,
		name: "Julieta",
		lastName: "López",
		age: 29,
		gender: "F",
		hobbies: ["cine", "yoga", "manualidades"],
	},
	{
		id: 1027,
		name: "Eduardo",
		lastName: "Torres",
		age: 33,
		gender: "M",
		hobbies: ["fotografía", "ajedrez", "tenis"],
	},
];
